version: '3'
services:
  application:
    image: "${IMAGE_NAME}"
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID = ${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY = ${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION = ${AWS_REGION}
      - AWS_ECR_LOGIN_URI = ${AWS_ECR_LOGIN_URI}
      - ECR_REPOSITORY_NAME = ${ECR_REPOSITORY_NAME}
      - MONGO_DB_URL = ${MONGO_DB_URL}
      - BUCKET_NAME = ${BUCKET_NAME}